basic.show_string("Megalovania Intro")
music.play_tone(294, music.beat(BeatFraction.HALF))
music.play_tone(294, music.beat(BeatFraction.HALF))
music.play_tone(587, music.beat(BeatFraction.HALF))
music.rest(music.beat(BeatFraction.HALF))
music.play_tone(440, music.beat(BeatFraction.HALF))
music.rest(music.beat(BeatFraction.WHOLE))
music.play_tone(415, music.beat(BeatFraction.HALF))
music.rest(music.beat(BeatFraction.HALF))
music.play_tone(392, music.beat(BeatFraction.HALF))
music.rest(music.beat(BeatFraction.HALF))
music.play_tone(349, music.beat(BeatFraction.WHOLE))
music.play_tone(294, music.beat(BeatFraction.HALF))
music.play_tone(349, music.beat(BeatFraction.HALF))
music.play_tone(392, music.beat(BeatFraction.HALF))
music.play_tone(277, music.beat(BeatFraction.HALF))
music.play_tone(277, music.beat(BeatFraction.HALF))
music.play_tone(587, music.beat(BeatFraction.HALF))
music.rest(music.beat(BeatFraction.HALF))
music.play_tone(440, music.beat(BeatFraction.HALF))
music.rest(music.beat(BeatFraction.WHOLE))
music.play_tone(415, music.beat(BeatFraction.HALF))
music.rest(music.beat(BeatFraction.HALF))
music.play_tone(392, music.beat(BeatFraction.HALF))
music.rest(music.beat(BeatFraction.HALF))
music.play_tone(349, music.beat(BeatFraction.WHOLE))
music.play_tone(294, music.beat(BeatFraction.HALF))
music.play_tone(349, music.beat(BeatFraction.HALF))
music.play_tone(392, music.beat(BeatFraction.HALF))
music.play_tone(262, music.beat(BeatFraction.HALF))
music.play_tone(262, music.beat(BeatFraction.HALF))
music.play_tone(587, music.beat(BeatFraction.HALF))
music.rest(music.beat(BeatFraction.HALF))
music.play_tone(440, music.beat(BeatFraction.HALF))
music.rest(music.beat(BeatFraction.WHOLE))
music.play_tone(415, music.beat(BeatFraction.HALF))
music.rest(music.beat(BeatFraction.HALF))
music.play_tone(392, music.beat(BeatFraction.HALF))
music.rest(music.beat(BeatFraction.HALF))
music.play_tone(349, music.beat(BeatFraction.WHOLE))
music.play_tone(294, music.beat(BeatFraction.HALF))
music.play_tone(349, music.beat(BeatFraction.HALF))
music.play_tone(392, music.beat(BeatFraction.HALF))
music.play_tone(247, music.beat(BeatFraction.HALF))
music.play_tone(247, music.beat(BeatFraction.HALF))
music.play_tone(587, music.beat(BeatFraction.HALF))
music.rest(music.beat(BeatFraction.HALF))
music.play_tone(440, music.beat(BeatFraction.HALF))
music.rest(music.beat(BeatFraction.WHOLE))
music.play_tone(415, music.beat(BeatFraction.HALF))
music.rest(music.beat(BeatFraction.HALF))
music.play_tone(392, music.beat(BeatFraction.HALF))
music.rest(music.beat(BeatFraction.HALF))
music.play_tone(349, music.beat(BeatFraction.WHOLE))
music.play_tone(294, music.beat(BeatFraction.HALF))
music.play_tone(349, music.beat(BeatFraction.HALF))
music.play_tone(392, music.beat(BeatFraction.HALF))
music.play_tone(311, music.beat(BeatFraction.HALF))
music.play_tone(311, music.beat(BeatFraction.HALF))
music.play_tone(622, music.beat(BeatFraction.HALF))
music.rest(music.beat(BeatFraction.HALF))
music.play_tone(466, music.beat(BeatFraction.HALF))
music.rest(music.beat(BeatFraction.WHOLE))
music.play_tone(440, music.beat(BeatFraction.HALF))
music.rest(music.beat(BeatFraction.HALF))
music.play_tone(415, music.beat(BeatFraction.HALF))
music.rest(music.beat(BeatFraction.HALF))
music.play_tone(370, music.beat(BeatFraction.WHOLE))
music.play_tone(311, music.beat(BeatFraction.HALF))
music.play_tone(370, music.beat(BeatFraction.HALF))
music.play_tone(415, music.beat(BeatFraction.HALF))
music.play_tone(294, music.beat(BeatFraction.HALF))
music.play_tone(294, music.beat(BeatFraction.HALF))
music.play_tone(622, music.beat(BeatFraction.HALF))
music.rest(music.beat(BeatFraction.HALF))
music.play_tone(466, music.beat(BeatFraction.HALF))
music.rest(music.beat(BeatFraction.WHOLE))
music.play_tone(440, music.beat(BeatFraction.HALF))
music.rest(music.beat(BeatFraction.HALF))
music.play_tone(415, music.beat(BeatFraction.HALF))
music.rest(music.beat(BeatFraction.HALF))
music.play_tone(370, music.beat(BeatFraction.WHOLE))
music.play_tone(311, music.beat(BeatFraction.HALF))
music.play_tone(370, music.beat(BeatFraction.HALF))
music.play_tone(415, music.beat(BeatFraction.HALF))
music.play_tone(277, music.beat(BeatFraction.HALF))
music.play_tone(277, music.beat(BeatFraction.HALF))
music.play_tone(622, music.beat(BeatFraction.HALF))
music.rest(music.beat(BeatFraction.HALF))
music.play_tone(466, music.beat(BeatFraction.HALF))
music.rest(music.beat(BeatFraction.WHOLE))
music.play_tone(440, music.beat(BeatFraction.HALF))
music.rest(music.beat(BeatFraction.HALF))
music.play_tone(415, music.beat(BeatFraction.HALF))
music.rest(music.beat(BeatFraction.HALF))
music.play_tone(370, music.beat(BeatFraction.WHOLE))
music.play_tone(311, music.beat(BeatFraction.HALF))
music.play_tone(370, music.beat(BeatFraction.HALF))
music.play_tone(415, music.beat(BeatFraction.HALF))
music.play_tone(262, music.beat(BeatFraction.HALF))
music.play_tone(262, music.beat(BeatFraction.HALF))
music.play_tone(622, music.beat(BeatFraction.HALF))
music.rest(music.beat(BeatFraction.HALF))
music.play_tone(466, music.beat(BeatFraction.HALF))
music.rest(music.beat(BeatFraction.WHOLE))
music.play_tone(440, music.beat(BeatFraction.HALF))
music.rest(music.beat(BeatFraction.HALF))
music.play_tone(415, music.beat(BeatFraction.HALF))
music.rest(music.beat(BeatFraction.HALF))
music.play_tone(370, music.beat(BeatFraction.WHOLE))
music.play_tone(311, music.beat(BeatFraction.HALF))
music.play_tone(370, music.beat(BeatFraction.HALF))
music.play_tone(415, music.beat(BeatFraction.HALF))